### PR TITLE
Rearchitecture simulate

### LINKED ISSUE #77: Decompose Simulate module into several source files
Module LPM/Simulate.jl is becoming larger and larger. The following is proposed:

```
module Simulate 
       ...
       include(simulate/helpfunc.jl")
       include("simulate/deaths.jl")
       include("simulate/births.jl") 
       include("simulate/marraiges.jl")     
       ...
end # Simulate 
```

### PR DESCRIPTION
**Pull request by AtiyahElsheikh**
resolves #77 

Going to work afterwards on #74 (refactoring iteration) & potentially #65 (lazy iterators)

### CODE REVIEW

**Comment by AtiyahElsheikh** [comment]
I have also fixed the arguments of checkassumptions & verbose in the main simualtion

**Comment by mhinsch** [comment]
Fine with me, but I think the return value of the main script should not be determined by verbose.

**Comment by AtiyahElsheikh** [comment]
- I started the re-factoring of main of for-loop body into a subroutine any way
- Allowing fixed & dynamic random seed generation ( default is fixed)

**Comment by AtiyahElsheikh** [comment]
Multiple simulations with fixed seed was still random. This is because inputs generation was not seed-dependent. This is not hopefully fixed

**Pull request merged**
