### PR TITLE
DoBirths()

### PR DESCRIPTION
**Pull request by AtiyahElsheikh**
This is initial plain translation of DoBirths()
It is the plain translation because it was started before writing the described model. I left an empty interface for DoBirthsOpt() that is going to be done in a later stage.
Sorry for the large number of commits. Got out of hand. Will try to reduce pull-request sizes in future.
I will lookup the conflict soon (probably due to the seed)

### CODE REVIEW

**Comment by AtiyahElsheikh** [comment]
yes, conflict resolved

**Comment by mhinsch** [comment]
Looks good. The only nitpick I have is that I would prefer functions to receive plain parameter objects without having to select the relevant sub-objects (see my comment on one of the commits). This is 1) simply a matter of keeping interfaces lean and 2) it makes it easier to change the layout of the parameter handling without having to change a gazillion small functions everywhere.

**Comment by AtiyahElsheikh** [comment]
[Explaination here](https://github.com/AtiyahElsheikh/LoneParentsModel.jl/commit/0782dfbd01c2a6d4d9fdc527dde0bb2971ee107e#commitcomment-83514523)

**Comment by AtiyahElsheikh** [comment]
the original way retained.

**Pull request merged**
