### PR TITLE
Transitions

### PR DESCRIPTION
**Pull request by mhinsch**
Runs but is not tested. This also includes a few small tidbits of the optimisation branch.

### CODE REVIEW

**Comment by AtiyahElsheikh** [comment]
Does it make sense to introduce a new Person type. Think about a purely demographic simulations without economic elements

**Comment by mhinsch** [comment]
I think the basic idea behind the current structure was that aggregate agent types (e.g. Person in this case) could be created as needed. So, we should create a new person type if we need one for a simulation that only does demography.
What I just realised while thinking about this, though - we should probably split out all the helper functions in person.jl. They can be reused as is in any person type that uses some of the same building blocks. I'll create an issue on that.

**Comment by AtiyahElsheikh** [comment]
I was thinking whether this shall be viewed as a Person-Type

What about something like that 

```
mutable struct X
  person::Person
  # the rest
end X 
```

Feel free to merge! or delay if you want to conduct tests first. 

But since it is so many new stuffs, please consider making a new release once merged!

**Comment by mhinsch** [comment]
> I was thinking whether this shall be viewed as a Person-Type
> 
> What about something like that
> 
> ```
> mutable struct X
>   person::Person
>   # the rest
> end X 
> ```

Could you elaborate, I don't understand what you mean with this.

**Pull request merged**
